console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
  template = '<cyan>{{ .PWD }}</> ➜ '
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'cyan'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' git:({{ if or (.Working.Changed) (.Staging.Changed) }}<yellow>{{ .HEAD }}</>{{ else }}<green>{{ .HEAD }}</>{{ end }}){{ if or (.Working.Changed) (.Staging.Changed) }} <yellow>✗</>{{ end }}'
    foreground = 'blue'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_ahead_icon = ''
      branch_behind_icon = ''
      branch_icon = ''
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .Venv }}(venv){{ end }} '
    foreground = 'cyan'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = '➜'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
