require("base16-colorscheme").setup({
    base00 = "#eceff4", -- bg0
    base01 = "#d8dee9", -- bg1
    base02 = "#bec5cd", -- bg2
    base03 = "#959da5", -- bg3
    base04 = "#6a737d", -- fg3
    base05 = "#47515c", -- fg2
    base06 = "#2f363d", -- fg1
    base07 = "#24292e", -- fg0
    base08 = "#99324B", -- red
    base09 = "#AC4426", -- orange
    base0A = "#9A7500", -- yellow
    base0B = "#4F894C", -- green
    base0C = "#29838D", -- aqua
    base0D = "#3B6EA8", -- blue
    base0E = "#97365B", -- purple
    base0F = "#398EAC", -- bonus
})
-- ((bg         '("#E5E9F0" nil       nil))
--    (bg-alt     '("#D8DEE9" nil       nil))
--    (base0      '("#F0F4FC" "black"   "black"))
--    (base1      '("#E3EAF5" "#1e1e1e" "brightblack"))
--    (base2      '("#D8DEE9" "#2e2e2e" "brightblack"))
--    (base3      '("#C2D0E7" "#262626" "brightblack"))
--    (base4      '("#B8C5DB" "#3f3f3f" "brightblack"))
--    (base5      '("#AEBACF" "#525252" "brightblack"))
--    (base6      '("#A1ACC0" "#6b6b6b" "brightblack"))
--    (base7      '("#60728C" "#979797" "brightblack"))
--    (base8      '("#485163" "#dfdfdf" "white"))
--    (fg         '("#3B4252" "#2d2d2d" "white"))
--    (fg-alt     '("#2E3440" "#bfbfbf" "brightwhite"))
--
--    (grey base4)
--    (red       '("#99324B" "#ff6655" "red"))
--    (orange    '("#AC4426" "#dd8844" "brightred"))
--    (green     '("#4F894C" "#99bb66" "green"))
--    (teal      '("#29838D" "#44b9b1" "brightgreen"))
--    (yellow    '("#9A7500" "#ECBE7B" "yellow"))
--    (blue      '("#3B6EA8" "#51afef" "brightblue"))
--    (dark-blue '("#5272AF" "#2257A0" "blue"))
--    (magenta   '("#97365B" "#c678dd" "magenta"))
--    (violet    '("#842879" "#a9a1e1" "brightmagenta"))
--    (cyan      '("#398EAC" "#46D9FF" "brightcyan"))
--    (dark-cyan '("#2C7088" "#5699AF" "cyan"))
-- "activityBar.activeBorder": "#f9826c",
--     "activityBar.background": "#d8dee9",
--     "activityBar.border": "#e1e4e8",
--     "activityBar.foreground": "#2f363d",
--     "activityBar.inactiveForeground": "#959da5",
--     "activityBarBadge.background": "#2a85cf",
--     "activityBarBadge.foreground": "#ffffff",
--     "badge.background": "#dbedff",
--     "badge.foreground": "#005cc5",
--     "breadcrumb.activeSelectionForeground": "#586069",
--     "breadcrumb.focusForeground": "#2f363d",
--     "breadcrumb.foreground": "#6a737d",
--     "breadcrumbPicker.background": "#fafbfc",
--     "button.background": "#159739",
--     "button.foreground": "#ffffff",
--     "button.hoverBackground": "#138934",
--     "checkbox.background": "#fafbfc",
--     "checkbox.border": "#d1d5da",
--     "debugToolBar.background": "#ffffff",
--     "descriptionForeground": "#6a737d",
--     "diffEditor.insertedTextBackground": "#34d05822",
--     "diffEditor.removedTextBackground": "#d73a4922",
--     "dropdown.background": "#fafbfc",
--     "dropdown.border": "#e1e4e8",
--     "dropdown.foreground": "#2f363d",
--     "dropdown.listBackground": "#ffffff",
--     "editor.background": "#eceff4",
--     "editor.findMatchBackground": "#ffdf5d",
--     "editor.findMatchHighlightBackground": "#ffdf5d66",
--     "editor.focusedStackFrameHighlightBackground": "#fff5b1",
--     "editor.foldBackground": "#fafbfc",
--     "editor.foreground": "#24292e",
--     "editor.inactiveSelectionBackground": "#0366d611",
--     "editor.lineHighlightBackground": "#f6f8fa",
--     "editor.selectionBackground": "#0366d625",
--     "editor.selectionHighlightBackground": "#34d05840",
--     "editor.selectionHighlightBorder": "#34d05800",
--     "editor.stackFrameHighlightBackground": "#fffbdd",
--     "editor.wordHighlightBackground": "#34d05800",
--     "editor.wordHighlightBorder": "#24943e99",
--     "editor.wordHighlightStrongBackground": "#34d05800",
--     "editor.wordHighlightStrongBorder": "#24943e50",
--     "editorBracketMatch.background": "#34d05840",
--     "editorBracketMatch.border": "#34d05800",
--     "editorCursor.foreground": "#044289",
--     "editorGroup.border": "#e1e4e8",
--     "editorGroup.dropBackground": "#e5e9f0",
--     "editorGroup.emptyBackground": "#e5e9f0",
--     "editorGroupHeader.noTabsBackground": "#e5e9f0",
--     "editorGroupHeader.tabsBackground": "#e5e9f0",
--     "editorGroupHeader.tabsBorder": "#e1e4e8",
--     "editorGutter.addedBackground": "#28a745",
--     "editorGutter.deletedBackground": "#d73a49",
--     "editorGutter.modifiedBackground": "#2188ff",
--     "editorIndentGuide.activeBackground": "#d7dbe0",
--     "editorIndentGuide.background": "#eff2f6",
--     "editorLineNumber.activeForeground": "#24292e",
--     "editorLineNumber.foreground": "#1b1f234d",
--     "editorOverviewRuler.border": "#ffffff",
--     "editorWhitespace.foreground": "#d1d5da",
--     "editorWidget.background": "#f6f8fa",
--     "errorForeground": "#cb2431",
--     "focusBorder": "#2188ff",
--     "foreground": "#444d56",
--     "gitDecoration.addedResourceForeground": "#28a745",
--     "gitDecoration.conflictingResourceForeground": "#e36209",
--     "gitDecoration.deletedResourceForeground": "#d73a49",
--     "gitDecoration.ignoredResourceForeground": "#959da5",
--     "gitDecoration.modifiedResourceForeground": "#005cc5",
--     "gitDecoration.submoduleResourceForeground": "#959da5",
--     "gitDecoration.untrackedResourceForeground": "#28a745",
--     "inlineTitleBar.background": "#e5e9f0",
--     "input.background": "#fafbfc",
--     "input.border": "#e1e4e8",
--     "input.foreground": "#2f363d",
--     "input.placeholderForeground": "#959da5",
--     "list.activeSelectionBackground": "#e2e5e9",
--     "list.activeSelectionForeground": "#2f363d",
--     "list.focusBackground": "#cce5ff",
--     "list.hoverBackground": "#ebf0f4",
--     "list.hoverForeground": "#2f363d",
--     "list.inactiveFocusBackground": "#dbedff",
--     "list.inactiveSelectionBackground": "#e8eaed",
--     "list.inactiveSelectionForeground": "#2f363d",
--     "notificationCenterHeader.background": "#e1e4e8",
--     "notificationCenterHeader.foreground": "#6a737d",
--     "notifications.background": "#fafbfc",
--     "notifications.border": "#e1e4e8",
--     "notifications.foreground": "#2f363d",
--     "notificationsErrorIcon.foreground": "#d73a49",
--     "notificationsInfoIcon.foreground": "#005cc5",
--     "notificationsWarningIcon.foreground": "#e36209",
--     "panel.background": "#f6f8fa",
--     "panel.border": "#e1e4e8",
--     "panelInput.border": "#e1e4e8",
--     "panelTitle.activeBorder": "#f9826c",
--     "panelTitle.activeForeground": "#2f363d",
--     "panelTitle.inactiveForeground": "#6a737d",
--     "pickerGroup.border": "#e1e4e8",
--     "pickerGroup.foreground": "#2f363d",
--     "progressBar.background": "#2188ff",
--     "quickInput.background": "#fafbfc",
--     "quickInput.foreground": "#2f363d",
--     "scrollbar.shadow": "#6a737d33",
--     "scrollbarSlider.activeBackground": "#959da588",
--     "scrollbarSlider.background": "#959da533",
--     "scrollbarSlider.hoverBackground": "#959da544",
--     "settings.headerForeground": "#2f363d",
--     "settings.modifiedItemIndicator": "#2188ff",
--     "sideBar.background": "#e5e9f0",
--     "sideBar.border": "#d8dee9",
--     "sideBar.foreground": "#586069",
--     "sideBarSectionHeader.background": "#d8dee9",
--     "sideBarSectionHeader.border": "#e1e4e8",
--     "sideBarSectionHeader.foreground": "#2f363d",
--     "sideBarTitle.foreground": "#2f363d",
--     "statusBar.background": "#e5e9f0",
--     "statusBar.border": "#e1e4e8",
--     "statusBar.debuggingBackground": "#f9826c",
--     "statusBar.debuggingForeground": "#ffffff",
--     "statusBar.foreground": "#586069",
--     "statusBar.noFolderBackground": "#ffffff",
--     "statusBarItem.prominentBackground": "#e8eaed",
--     "statusBarItem.remoteBackground": "#e5e9f0",
--     "statusBarItem.remoteForeground": "#000000",
--     "tab.activeBackground": "#eceff4",
--     "tab.activeBorder": "#ffffff",
--     "tab.activeBorderTop": "#f9826c",
--     "tab.activeForeground": "#2f363d",
--     "tab.border": "#d8dee9",
--     "tab.hoverBackground": "#ffffff",
--     "tab.inactiveBackground": "#e5e9f0",
--     "tab.inactiveForeground": "#6a737d",
--     "tab.unfocusedActiveBorder": "#ffffff",
--     "tab.unfocusedActiveBorderTop": "#e1e4e8",
--     "tab.unfocusedHoverBackground": "#ffffff",
--     "terminal.foreground": "#586069",
--     "textBlockQuote.background": "#fafbfc",
--     "textBlockQuote.border": "#e1e4e8",
--     "textCodeBlock.background": "#f6f8fa",
-- 		"textLink.activeForeground": "#032F62",
-- 		"textLink.foreground": "#032F62",
--     "textPreformat.foreground": "#586069",
--     "textSeparator.foreground": "#d1d5da",
--     "titleBar.activeBackground": "#e5e9f0",
--     "titleBar.activeForeground": "#2f363d",
--     "titleBar.border": "#e1e4e8",
--     "titleBar.inactiveBackground": "#f6f8fa",
--     "titleBar.inactiveForeground": "#6a737d",
--     "tree.indentGuidesStroke": "#e1e4e8",
--     "welcomePage.buttonBackground": "#f6f8fa",
--     "welcomePage.buttonHoverBackground": "#e1e4e8",
--   },
